version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword

  go-producer:
    build: ./go-producer
    depends_on:
      - rabbitmq
    ports:
      - "3099:3000" # HTTP API port
    environment:
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672/

  go-consumer:
    build: ./go-consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://myuser:mypassword@rabbitmq:5672/
